### ISSUE TITLE
Even using `with-db`, the `oui.tsv` file still needs to be local.

### ISSUE THREAD

**Issue by bgillespie** [marirs/mac-oui#1]
Unless I've misunderstood how `Oui::default` is meant to work, the path `assets/oui.csv` still needs to be present whilst using the `with-db` feature flag. If I build an executable and move it somewhere it can't see that path, it bails saying that it can't find the file.

I cloned the repo, deleted [this check](https://github.com/marirs/mac-oui/blob/e4a0c5e4a60eba5d94a5b9e2fe1fc1df8941b474/src/oui.rs#L76), and now it does what I expect: to have the OUI database built in without needing the dir and CSV file near the executable.

**Comment by marirs** [comment]
You'r actually right. I'm sorry. I missed that out...
I initially did not have it, but then later I added just to check if that folder and the file remains. My bad.
I have removed that check now, and its updated including in crates.io with:
`mac_oui = "0.3.1"`

Thank you very much for pointing that out

**Comment by bgillespie** [comment]
No worries. Thanks so much for the prompt fix!
